CREATE DATABASE MIDFINAL1;

USE MIDFINAL1;

CREATE TABLE DEVELOPERS (
    DEVID INT PRIMARY KEY,
    DEVNAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    BASESALARY INT,
    JOINDATE DATE,
    EMAIL VARCHAR(100)
);

CREATE TABLE PROJECT (
    PROJECTID VARCHAR(5) PRIMARY KEY,
    PROJECTNAME VARCHAR(100),
    CLIENT VARCHAR(100),
    BUDGET INT,
    STATUS VARCHAR(20)
);

CREATE TABLE PROJECTALLOCATIONS (
    ALLOCID INT PRIMARY KEY,
    DEVID INT,
    PROJECTID VARCHAR(5),
    ALLOCHOURS INT,
    ROLE VARCHAR(50),
    FOREIGN KEY (DEVID) REFERENCES DEVELOPERS(DEVID),
    FOREIGN KEY (PROJECTID) REFERENCES PROJECT(PROJECTID)
);

INSERT INTO DEVELOPERS VALUES
(1, 'ALICE SMITH', 'FRONTEND', 55000, '2021-05-10', 'ALICE@TECH.COM'),
(2, 'BOB JOHNSON', 'BACKEND', 72000, '2020-08-15', 'BOB@DEV.NET'),
(3, 'CHARLIE BROWN', 'DEVOPS', 65000, '2022-01-20', 'CHARLIE@TECH.COM'),
(4, 'DIANA PRINCE', 'BACKEND', 80000, '2019-11-05', 'DIANA@DEV.NET'),
(5, 'EVAN WRIGHT', 'FRONTEND', 48000, '2023-03-01', 'EVAN@TECH.COM'),
(6, 'FIONA GALLAGHER', 'DATA SCIENCE', 95000, '2018-07-22', 'FIONA@DATA.ORG'),
(7, 'GEORGE LUCAS', 'BACKEND', 61000, '2022-09-10', 'GEORGE@DEV.NET'),
(8, 'HANNAH ABBOTT', 'DEVOPS', 68000, '2021-12-12', 'HANNAH@TECH.COM'),
(9, 'IAN SOMERHALDER', 'FRONTEND', 52000, '2022-05-30', 'IAN@TECH.COM'),
(10, 'JANE DOE', 'DATA SCIENCE', 89000, '2020-02-18', 'JANE@DATA.ORG');

INSERT INTO PROJECT VALUES
('P1', 'PROJECT ALPHA', 'TECHCORP', 500000, 'ACTIVE'),
('P2', 'PROJECT BETA', 'HEALTHINC', 300000, 'ACTIVE'),
('P3', 'PROJECT GAMMA', 'FINBANK', 750000, 'COMPLETED'),
('P4', 'PROJECT DELTA', 'EDUNET', 200000, 'ACTIVE');

INSERT INTO PROJECTALLOCATIONS VALUES
(101, 2, 'P1', 120, 'LEAD'),
(102, 1, 'P1', 80, 'DEVELOPER'),
(103, 4, 'P2', 150, 'LEAD'),
(104, 6, 'P3', 200, 'DATA ARCHITECT'),
(105, 3, 'P1', 100, 'OPS MANAGER'),
(106, 7, 'P2', 90, 'DEVELOPER'),
(107, 10, 'P3', 180, 'ANALYST'),
(108, 5, 'P4', 60, 'UI/UX'),
(109, 8, 'P2', 110, 'OPS MANAGER'),
(110, 9, 'P4', 70, 'DEVELOPER');

-------------------------------------------
--MID ASSESMENT QUESTIONS
-------------------------------------------

--Q1
UPDATE DEVELOPERS
SET BASESALARY = 
    CASE 
        WHEN BASESALARY * 1.15 > 85000 THEN 85000
        ELSE BASESALARY * 1.15
    END
WHERE DEPARTMENT = 'BACKEND'
AND JOINDATE < '2022-01-01';


--Q2
SELECT 
    UPPER(DEVNAME) AS UNAME,
    LEN(EMAIL) AS EMAIL_LENGTH,
    DATEDIFF(MONTH, JOINDATE, GETDATE()) AS EXPERIENCE
FROM DEVELOPERS
WHERE DATEDIFF(MONTH, JOINDATE, GETDATE()) > 24;

--Q3
SELECT DEVNAME, DEPARTMENT, BASESALARY
FROM DEVELOPERS
ORDER BY BASESALARY DESC
OFFSET 3 ROWS
FETCH NEXT 4 ROWS ONLY;


--Q4
SELECT PROJECTID, 
       COUNT(DEVID) AS T_DEV, 
       SUM(ALLOCHOURS) AS T_ALLOC
FROM PROJECTALLOCATIONS
GROUP BY PROJECTID
HAVING SUM(ALLOCHOURS) > 150
ORDER BY T_ALLOC DESC;


--Q5
-- Add UNIQUE constraint
ALTER TABLE DEVELOPERS
ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL);
-- Add CHECK constraint
ALTER TABLE DEVELOPERS
ADD CONSTRAINT CHK_SALARY CHECK (BASESALARY >= 45000);

-----------------------------------------------
--MORE QUERYS AS PER MID FINAL PRACTICE PDF
-----------------------------------------------

--1
UPDATE DEVELOPERS
SET BASESALARY =
    CASE 
        WHEN (BASESALARY * 1.12) > 90000 THEN 90000
        ELSE (BASESALARY * 1.12)
    END
WHERE DEPARTMENT = 'DEVOPS' 
AND JOINDATE = '2021-01-05' ;

--2
SELECT 
    LOWER(DEVNAME) AS LOWNAME,
    SUBSTRING(EMAIL,1,CHARINDEX('@',EMAIL)-1) AS DOMAIS,
    DATEDIFF(YEAR,JOINDATE,GETDATE()) AS EXPERIENCE
FROM DEVELOPERS
WHERE DATEDIFF(YEAR,JOINDATE,GETDATE()) > 3;

--3
SELECT 
    DEVNAME, DEPARTMENT,BASESALARY
FROM DEVELOPERS
ORDER BY DEVID 
OFFSET 5 ROWS
FETCH NEXT 4 ROWS ONLY;

--4
SELECT 
    PROJECTID,
    COUNT(DEVID) AS TOTALDEVELOPER,
    SUM(ALLOCHOURS) AS TOTALALLOC
FROM PROJECTALLOCATIONS
GROUP BY PROJECTID
HAVING SUM(ALLOCHOURS) > 100
ORDER BY TOTALALLOC DESC;

--5
ALTER TABLE DEVELOPER 
ADD CONSTRAINT UQ_EMAIL UNIQUE(EMAIL);

ALTER TABLE DEVELOPER
ADD CONSTRAINT CHECK_SALARY CHECK(BASESALARY >= 45000);

ALTER TABLE DEVELOPER 
ADD CONSTRAINT DFF_JOINDATE DEFAULT GATEDATE() FOR JOINDATE;

--6
UPDATE DEVELOPERS
    SET BASESALARY = 
        CASE 
            WHEN BASESALARY * 1.10 < 80000 THEN 80000
            ELSE BASESALARY * 1.10
        END
WHERE DEPARTMENT = 'FRONTEND' 
AND JOINDATE < '2020-01-01';

--7
SELECT 
    UPPER(DEVNAME) AS UP_DEVNAME,
    SUBSTRING(EMAIL,1,5) AS FIRST_5,
    DATEDIFF(DAY,JOINDATE,GETDATE()) AS TOTAL_DAY
FROM DEVELOPERS
WHERE DATEDIFF(DAY,JOINDATE,GETDATE()) > 1000

SELECT * FROM DEVELOPERS;
SELECT * FROM PROJECT;
SELECT * FROM PROJECTALLOCATIONS;